### ISSUE TITLE
Langgraph cloud deployment failing suddenly

### ISSUE THREAD

**Issue by SeveHo** [langchain-ai/langgraph#5694]
### Checked other resources

- [x] This is a bug, not a usage question. For questions, please use the LangChain Forum (https://forum.langchain.com/).
- [x] I added a clear and detailed title that summarizes the issue.
- [x] I read what a minimal reproducible example is (https://stackoverflow.com/help/minimal-reproducible-example).
- [x] I included a self-contained, minimal example that demonstrates the issue INCLUDING all the relevant imports. The code run AS IS to reproduce the issue.

### Example Code

```python
Seems irrelevant.
```

### Error Message and Stack Trace (if applicable)

```shell
[INFO] ERROR: build step 14 "langchain/hosted-langgraph-api-build" failed: step exited with non-zero status: 1
[INFO] ERROR
[INFO] Finished Step #14
[INFO] Step #14: WORKDIR /deps/__outer_agents/src
[INFO] Step #14: RUN uv pip uninstall --system pip setuptools wheel && rm /usr/bin/uv /usr/bin/uvx
[INFO] Step #14: RUN rm -rf /usr/lib/python*/site-packages/pip* /usr/lib/python*/site-packages/setuptools* /usr/lib/python*/site-packages/wheel* && find /usr/bin -name "pip*" -delete || true
[INFO] Step #14: RUN rm -rf /usr/local/lib/python*/site-packages/pip* /usr/local/lib/python*/site-packages/setuptools* /usr/local/lib/python*/site-packages/wheel* && find /usr/local/bin -name "pip*" -delete || true
[INFO] Step #14: RUN pip uninstall -y pip setuptools wheel
[INFO] Step #14: # -- Removing build deps from the final image ~<:===~~~ --
[INFO] Step #14: # -- End of ensuring user deps didn't inadvertently overwrite langgraph-api --
```

### Description

Today suddenly my langgraph deployments stopped working with this message:
```
An error occurred while creating a Docker image from your specified GitHub repository. Please see your build logs (by clicking on the revision) for more information.
```
And the build log above.

My versions are pinned but it seems somewhat related to the release of langgraph 0.6.0 as it started happening right around the time the release was announced. This is an urgent issue as we can't roll out any new revision anymore.

### System Info

Package Information
-------------------
> langchain_core: 0.3.72
> langchain: 0.3.27
> langsmith: 0.4.8
> langchain_anthropic: 0.3.17
> langchain_google_genai: 2.1.8
> langchain_groq: 0.3.6
> langchain_openai: 0.3.28
> langchain_text_splitters: 0.3.9
> langgraph_api: 0.2.102
> langgraph_cli: 0.3.6
> langgraph_license: Installed. No version info available.
> langgraph_runtime: Installed. No version info available.
> langgraph_runtime_inmem: 0.6.1
> langgraph_sdk: 0.1.74

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> anthropic<1,>=0.57.0: Installed. No version info available.
> async-timeout<5.0.0,>=4.0.0;: Installed. No version info available.
> blockbuster<2.0.0,>=1.5.24: Installed. No version info available.
> click>=8.1.7: Installed. No version info available.
> cloudpickle>=3.0.0: Installed. No version info available.
> cryptography<45.0,>=42.0.0: Installed. No version info available.
> filetype: 1.2.0
> google-ai-generativelanguage: 0.6.18
> groq<1,>=0.29.0: Installed. No version info available.
> httpx: 0.28.1
> httpx>=0.25.0: Installed. No version info available.
> httpx>=0.25.2: Installed. No version info available.
> jsonpatch<2.0,>=1.33: Installed. No version info available.
> jsonschema-rs<0.30,>=0.20.0: Installed. No version info available.
> langchain-anthropic;: Installed. No version info available.
> langchain-aws;: Installed. No version info available.
> langchain-azure-ai;: Installed. No version info available.
> langchain-cohere;: Installed. No version info available.
> langchain-community;: Installed. No version info available.
> langchain-core<1.0.0,>=0.3.68: Installed. No version info available.
> langchain-core<1.0.0,>=0.3.72: Installed. No version info available.
> langchain-core>=0.3.64: Installed. No version info available.
> langchain-deepseek;: Installed. No version info available.
> langchain-fireworks;: Installed. No version info available.
> langchain-google-genai;: Installed. No version info available.
> langchain-google-vertexai;: Installed. No version info available.
> langchain-groq;: Installed. No version info available.
> langchain-huggingface;: Installed. No version info available.
> langchain-mistralai;: Installed. No version info available.
> langchain-ollama;: Installed. No version info available.
> langchain-openai;: Installed. No version info available.
> langchain-perplexity;: Installed. No version info available.
> langchain-text-splitters<1.0.0,>=0.3.9: Installed. No version info available.
> langchain-together;: Installed. No version info available.
> langchain-xai;: Installed. No version info available.
> langgraph-api<0.3.0,>=0.2.67;: Installed. No version info available.
> langgraph-checkpoint>=2.0.23: Installed. No version info available.
> langgraph-checkpoint>=2.0.25: Installed. No version info available.
> langgraph-runtime-inmem<0.7,>=0.6.0: Installed. No version info available.
> langgraph-runtime-inmem>=0.6.0;: Installed. No version info available.
> langgraph-sdk>=0.1.0;: Installed. No version info available.
> langgraph-sdk>=0.1.74: Installed. No version info available.
> langgraph>=0.2: Installed. No version info available.
> langgraph>=0.3.27: Installed. No version info available.
> langsmith-pyo3: Installed. No version info available.
> langsmith>=0.1.17: Installed. No version info available.
> langsmith>=0.3.45: Installed. No version info available.
> openai-agents: Installed. No version info available.
> openai<2.0.0,>=1.86.0: Installed. No version info available.
> opentelemetry-api: Installed. No version info available.
> opentelemetry-exporter-otlp-proto-http: Installed. No version info available.
> opentelemetry-sdk: Installed. No version info available.
> orjson: 3.11.1
> orjson>=3.10.1: Installed. No version info available.
> orjson>=3.9.7: Installed. No version info available.
> packaging: 25.0
> packaging>=23.2: Installed. No version info available.
> pydantic: 2.11.7
> pydantic<3.0.0,>=2.7.4: Installed. No version info available.
> pydantic>=2.7.4: Installed. No version info available.
> pyjwt>=2.9.0: Installed. No version info available.
> pytest: 8.4.1
> python-dotenv>=0.8.0;: Installed. No version info available.
> PyYAML>=5.3: Installed. No version info available.
> requests: 2.32.4
> requests-toolbelt: 1.0.0
> requests<3,>=2: Installed. No version info available.
> rich: Installed. No version info available.
> SQLAlchemy<3,>=1.4: Installed. No version info available.
> sse-starlette<2.2.0,>=2.1.0: Installed. No version info available.
> sse-starlette>=2: Installed. No version info available.
> starlette>=0.37: Installed. No version info available.
> starlette>=0.38.6: Installed. No version info available.
> structlog<26,>=24.1.0: Installed. No version info available.
> structlog>23: Installed. No version info available.
> tenacity!=8.4.0,<10.0.0,>=8.1.0: Installed. No version info available.
> tenacity>=8.0.0: Installed. No version info available.
> tiktoken<1,>=0.7: Installed. No version info available.
> truststore>=0.1: Installed. No version info available.
> typing-extensions>=4.7: Installed. No version info available.
> uvicorn>=0.26.0: Installed. No version info available.
> watchfiles>=0.13: Installed. No version info available.
> zstandard: 0.23.0

**Comment by SeveHo** [comment]
**Update:** it worked by upgrading to to 0.6.0. Just had to wait until langmem 0.0.29 was released as [0.0.28 is not compatible](https://github.com/langchain-ai/langmem/issues/104#issuecomment-3129005243). However, I have to pin langgraph-api to 0.2.102 because when I use 0.2.109 running `langgraph dev` fails with the following error:
```
[error    ] Traceback (most recent call last):
  File ".venv/lib/python3.13/site-packages/starlette/routing.py", line 694, in lifespan
    async with self.lifespan_context(app) as maybe_state:
               ~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 214, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.13/site-packages/langgraph_runtime_inmem/lifespan.py", line 62, in lifespan
    if feature_flags.USE_RUNTIME_API:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'langgraph_api.feature_flags' has no attribute 'USE_RUNTIME_API'
```

Current requirements.txt:
```
langsmith==0.4.8
langgraph==0.6.0
langgraph-cli==0.3.6
langgraph-cli[inmem]==0.3.6
langchain[openai]==0.3.27
langchain[google-genai]==0.3.27
langchain[anthropic]==0.3.27
pytest>=8.4.0
requests==2.32.4
PyJWT[crypto]==2.10.1
langchain-groq==0.3.6
langmem==0.0.29
langgraph-api==0.2.109
```

**Comment by sydney-runkle** [comment]
Yep, only latest versions of API work well with v0.6.0. We're going to keep tighter bounds in the future to prevent issues like this. Thanks for the report!

**Comment by SeveHo** [comment]
Appreciate the response @sydney-runkle. However, this does not fix my issue. I cannot update to 0.6.0 because the new context API does not work yet with langgraph js sdk and the react useStream hook and staying at 0.5.4 doesn't work either because then the cloud deployment build fails with the issue below. What do you suggest your cloud customers that can't upgrade to 0.6.0 yet?

For completeness, i have included the full log below:
```
ERROR: build step 14 "langchain/hosted-langgraph-api-build" failed: step exited with non-zero status: 1
ERROR
Finished Step #14
Step #14: WORKDIR /deps/__outer_agents/src
Step #14: RUN uv pip uninstall --system pip setuptools wheel && rm /usr/bin/uv /usr/bin/uvx
Step #14: RUN rm -rf /usr/lib/python*/site-packages/pip* /usr/lib/python*/site-packages/setuptools* /usr/lib/python*/site-packages/wheel* && find /usr/bin -name "pip*" -delete || true
Step #14: RUN rm -rf /usr/local/lib/python*/site-packages/pip* /usr/local/lib/python*/site-packages/setuptools* /usr/local/lib/python*/site-packages/wheel* && find /usr/local/bin -name "pip*" -delete || true
Step #14: RUN pip uninstall -y pip setuptools wheel
Step #14: # -- Removing build deps from the final image ~<:===~~~ --
Step #14: # -- End of ensuring user deps didn't inadvertently overwrite langgraph-api --
Step #14: RUN PYTHONDONTWRITEBYTECODE=1 uv pip install --system --no-cache-dir --no-deps -e /api
Step #14: RUN mkdir -p /api/langgraph_api /api/langgraph_runtime /api/langgraph_license && touch /api/langgraph_api/__init__.py /api/langgraph_runtime/__init__.py /api/langgraph_license/__init__.py
Step #14: # -- Ensure user deps didn't inadvertently overwrite langgraph-api
Step #14: ENV LANGSERVE_GRAPHS='{"abc": "/deps/__outer_agents/src/graphs/abc/graph.py:graph", "xyz": "/deps/__outer_agents/src/graphs/xyz/graph.py:graph"}'
Step #14: ENV LANGGRAPH_AUTH='{"path": "/deps/__outer_agents/src/security/auth.py:auth"}'
Step #14: # -- End of local dependencies install --
Step #14: RUN PYTHONDONTWRITEBYTECODE=1 uv pip install --system --no-cache-dir -c /api/constraints.txt -e /deps/*
Step #14: # -- Installing all local dependencies --
Step #14: # -- End of non-package dependency agents --
Step #14:     done
Step #14:         echo "$line" >> /deps/__outer_agents/pyproject.toml; \
Step #14:                 'build-backend = "setuptools.build_meta"'; do \
Step #14:                 'requires = ["setuptools>=61"]' \
Step #14:                 '[build-system]' \
Step #14:                 '"*" = ["**/*"]' \
Step #14:                 '[tool.setuptools.package-data]' \
Step #14:                 'version = "0.1"' \
Step #14:                 'name = "agents"' \
Step #14:     for line in '[project]' \
Step #14: RUN set -ex && \
Step #14: ADD . /deps/__outer_agents/src
Step #14: # -- Adding non-package dependency agents --
Step #14: # -- End of local requirements install --
Step #14: RUN PYTHONDONTWRITEBYTECODE=1 uv pip install --system --no-cache-dir -c /api/constraints.txt -r /deps/__outer_agents/src/requirements.txt
Step #14: ADD requirements.txt /deps/__outer_agents/src/requirements.txt
Step #14: # -- Installing local requirements --
Step #14: FROM gcr.io/langchain-prod/langgraph-api-unlicensed:3.11
Step #14: + docker build -f - -t us-west1-docker.pkg.dev/langchain-prod/langgraph-cloud-builds/<redacted> /workspace/agents <
Step #14: + docker pull gcr.io/langchain-prod/langgraph-api-unlicensed:3.11
Step #14: ERROR: failed to build: failed to solve: executor failed running [/bin/sh -c PYTHONDONTWRITEBYTECODE=1 uv pip install --system --no-cache-dir -c /api/constraints.txt -r /deps/__outer_agents/src/requirements.txt]: exit code: 1
Step #14: ------
Step #14: 0.570       requirements are unsatisfiable.
Step #14: 0.570       And because you require langgraph==0.5.4, we can conclude that your
Step #14: 0.570       used.
Step #14: 0.570       langgraph-sdk>=0.2.0, we can conclude that langgraph==0.5.4 cannot be
Step #14: 0.570   ╰─▶ Because langgraph==0.5.4 depends on langgraph-sdk>=0.1.42,<0.2.0 and
Step #14: ERROR: failed to build: failed to solve: executor failed running [/bin/sh -c PYTHONDONTWRITEBYTECODE=1 uv pip install --system --no-cache-dir -c /api/constraints.txt -r /deps/__outer_agents/src/requirements.txt]: exit code: 1
Step #14: ------
Step #14: 0.570       requirements are unsatisfiable.
Step #14: 0.570       And because you require langgraph==0.5.4, we can conclude that your
Step #14: 0.570       used.
Step #14: 0.570       langgraph-sdk>=0.2.0, we can conclude that langgraph==0.5.4 cannot be
Step #14: 0.570   ╰─▶ Because langgraph==0.5.4 depends on langgraph-sdk>=0.1.42,<0.2.0 and
Step #14: 0.570   × No solution found when resolving dependencies:
Step #14: 0.426 Using Python 3.11.13 environment at: /usr/local
Step #14:  > [ 3/13] RUN PYTHONDONTWRITEBYTECODE=1 uv pip install --system --no-cache-dir -c /api/constraints.txt -r /deps/__outer_agents/src/requirements.txt:
Step #14: ------
Step #14: #7 ERROR: executor failed running [/bin/sh -c PYTHONDONTWRITEBYTECODE=1 uv pip install --system --no-cache-dir -c /api/constraints.txt -r /deps/__outer_agents/src/requirements.txt]: exit code: 1
Step #14: #7 0.570       requirements are unsatisfiable.
Step #14: #7 0.570       And because you require langgraph==0.5.4, we can conclude that your
Step #14: #7 0.570       used.
Step #14: #7 0.570       langgraph-sdk>=0.2.0, we can conclude that langgraph==0.5.4 cannot be
Step #14: #7 0.570   ╰─▶ Because langgraph==0.5.4 depends on langgraph-sdk>=0.1.42,<0.2.0 and
Step #14: #7 0.570   × No solution found when resolving dependencies:
Step #14: #7 0.426 Using Python 3.11.13 environment at: /usr/local
Step #14: #7 [ 3/13] RUN PYTHONDONTWRITEBYTECODE=1 uv pip install --system --no-cache-dir -c /api/constraints.txt -r /deps/__outer_agents/src/requirements.txt
Step #14: 
Step #14: #6 DONE 1.8s
Step #14: #6 [ 2/13] ADD requirements.txt /deps/__outer_agents/src/requirements.txt
Step #14: 
Step #14: #5 DONE 0.3s
Step #14: #5 [ 1/13] FROM gcr.io/langchain-prod/langgraph-api-unlicensed:3.11
Step #14: 
Step #14: #4 DONE 0.1s
Step #14: #4 transferring context: 4.70MB 0.0s done
Step #14: #4 [internal] load build context
Step #14: 
Step #14: #3 DONE 0.0s
Step #14: #3 [internal] load metadata for gcr.io/langchain-prod/langgraph-api-unlicensed:3.11
Step #14: 
Step #14: #2 DONE 0.0s
Step #14: #2 transferring context: 2B done
Step #14: #2 [internal] load .dockerignore
Step #14: 
Step #14: #1 DONE 0.0s
Step #14: #1 transferring dockerfile: 2.37kB done
Step #14: #1 [internal] load build definition from Dockerfile
Step #14: 
Step #14: #0 building with "default" instance using docker driver
Step #14: 0.570   × No solution found when resolving dependencies:
Step #14: 0.426 Using Python 3.11.13 environment at: /usr/local
Step #14:  > [ 3/13] RUN PYTHONDONTWRITEBYTECODE=1 uv pip install --system --no-cache-dir -c /api/constraints.txt -r /deps/__outer_agents/src/requirements.txt:
Step #14: ------
Step #14: #7 ERROR: executor failed running [/bin/sh -c PYTHONDONTWRITEBYTECODE=1 uv pip install --system --no-cache-dir -c /api/constraints.txt -r /deps/__outer_agents/src/requirements.txt]: exit code: 1
Step #14: #7 0.570       requirements are unsatisfiable.
Step #14: #7 0.570       And because you require langgraph==0.5.4, we can conclude that your
Step #14: #7 0.570       used.
Step #14: #7 0.570       langgraph-sdk>=0.2.0, we can conclude that langgraph==0.5.4 cannot be
Step #14: #7 0.570   ╰─▶ Because langgraph==0.5.4 depends on langgraph-sdk>=0.1.42,<0.2.0 and
Step #14: #7 0.570   × No solution found when resolving dependencies:
Step #14: #7 0.426 Using Python 3.11.13 environment at: /usr/local
Step #14: #7 [ 3/13] RUN PYTHONDONTWRITEBYTECODE=1 uv pip install --system --no-cache-dir -c /api/constraints.txt -r /deps/__outer_agents/src/requirements.txt
Step #14: 
Step #14: #6 DONE 1.8s
Step #14: #6 [ 2/13] ADD requirements.txt /deps/__outer_agents/src/requirements.txt
Step #14: 
Step #14: #5 DONE 0.3s
Step #14: #5 [ 1/13] FROM gcr.io/langchain-prod/langgraph-api-unlicensed:3.11
Step #14: 
Step #14: #4 DONE 0.1s
Step #14: #4 transferring context: 4.70MB 0.0s done
Step #14: #4 [internal] load build context
Step #14: 
Step #14: #3 DONE 0.0s
Step #14: #3 [internal] load metadata for gcr.io/langchain-prod/langgraph-api-unlicensed:3.11
Step #14: 
Step #14: #2 DONE 0.0s
Step #14: #2 transferring context: 2B done
Step #14: #2 [internal] load .dockerignore
Step #14: 
Step #14: #1 DONE 0.0s
Step #14: #1 transferring dockerfile: 2.37kB done
Step #14: #1 [internal] load build definition from Dockerfile
Step #14: 
Step #14: #0 building with "default" instance using docker driver
Step #14: gcr.io/langchain-prod/langgraph-api-unlicensed:3.11
Step #14: Status: Downloaded newer image for gcr.io/langchain-prod/langgraph-api-unlicensed:3.11
Step #14: Digest: sha256:d43909d1c66a3406346d62a44de9b47df0f4502fafeaad238c34a70af7d7d181
Step #14: 1676a08c68ff: Pull complete
Step #14: faa40c0daee3: Pull complete
Step #14: c55766535c94: Pull complete
Step #14: 4f4fb700ef54: Pull complete
Step #14: d3d256e787d7: Pull complete
Step #14: 7e1c01959814: Pull complete
Step #14: 7823f4f935f9: Pull complete
Step #14: c3383807a572: Pull complete
Step #14: 81e1b44caf27: Pull complete
Step #14: 25c4d3ef10f0: Pull complete
Step #14: 0c0a29672d42: Pull complete
Step #14: 4085babbc570: Pull complete
Step #14: b7b61708209a: Pull complete
Step #14: 1676a08c68ff: Download complete
Step #14: 1676a08c68ff: Verifying Checksum
Step #14: faa40c0daee3: Download complete
Step #14: faa40c0daee3: Verifying Checksum
Step #14: d3d256e787d7: Download complete
Step #14: d3d256e787d7: Verifying Checksum
Step #14: c55766535c94: Download complete
Step #14: c55766535c94: Verifying Checksum
Step #14: abd846fa1cdb: Pull complete
Step #14: 4f4fb700ef54: Download complete
Step #14: 59e22667830b: Pull complete
Step #14: c3383807a572: Download complete
Step #14: c3383807a572: Verifying Checksum
Step #14: 7e1c01959814: Download complete
Step #14: 7e1c01959814: Verifying Checksum
Step #14: 7823f4f935f9: Download complete
Step #14: 7823f4f935f9: Verifying Checksum
Step #14: 81e1b44caf27: Download complete
Step #14: 81e1b44caf27: Verifying Checksum
Step #14: 0c0a29672d42: Download complete
Step #14: 0c0a29672d42: Verifying Checksum
Step #14: 25c4d3ef10f0: Download complete
Step #14: 25c4d3ef10f0: Verifying Checksum
Step #14: 4085babbc570: Download complete
Step #14: 4085babbc570: Verifying Checksum
Step #14: 59e22667830b: Download complete
Step #14: 59e22667830b: Verifying Checksum
Step #14: b7b61708209a: Download complete
Step #14: b7b61708209a: Verifying Checksum
Step #14: abd846fa1cdb: Download complete
Step #14: abd846fa1cdb: Verifying Checksum
Step #14: 4085babbc570: Waiting
Step #14: 7823f4f935f9: Waiting
Step #14: 81e1b44caf27: Waiting
Step #14: c3383807a572: Waiting
Step #14: 25c4d3ef10f0: Waiting
Step #14: 0c0a29672d42: Waiting
Step #14: 1676a08c68ff: Waiting
Step #14: 4f4fb700ef54: Waiting
Step #14: faa40c0daee3: Waiting
Step #14: d3d256e787d7: Waiting
Step #14: c55766535c94: Waiting
Step #14: 7e1c01959814: Waiting
Step #14: 1676a08c68ff: Pulling fs layer
Step #14: faa40c0daee3: Pulling fs layer
Step #14: c55766535c94: Pulling fs layer
Step #14: 4f4fb700ef54: Pulling fs layer
Step #14: d3d256e787d7: Pulling fs layer
Step #14: 7e1c01959814: Pulling fs layer
Step #14: 7823f4f935f9: Pulling fs layer
Step #14: c3383807a572: Pulling fs layer
Step #14: 81e1b44caf27: Pulling fs layer
Step #14: 25c4d3ef10f0: Pulling fs layer
Step #14: 0c0a29672d42: Pulling fs layer
Step #14: 4085babbc570: Pulling fs layer
Step #14: b7b61708209a: Pulling fs layer
Step #14: abd846fa1cdb: Pulling fs layer
```

**Comment by dqbd** [comment]
Hello! `context` prop is available from `@langchain/langgraph-sdk` with `0.0.103`, `useStream` support will add support in this PR: https://github.com/langchain-ai/langgraphjs/pull/1462
