### ISSUE TITLE
Command: goto argument is not working. TypeError: Command.__init__() got an unexpected keyword argument 'goto'

### ISSUE THREAD

**Issue by Saisiva123** [langchain-ai/langgraph#2844]
### Checked other resources

- [X] This is a bug, not a usage question. For questions, please use GitHub Discussions.
- [X] I added a clear and detailed title that summarizes the issue.
- [X] I read what a minimal reproducible example is (https://stackoverflow.com/help/minimal-reproducible-example).
- [X] I included a self-contained, minimal example that demonstrates the issue INCLUDING all the relevant imports. The code run AS IS to reproduce the issue.

### Example Code

```python
return Command(goto="multiplication_expert", update={"messages": [ai_msg, tool_msg]})
The above code is throwing the error.
```

### Error Message and Stack Trace (if applicable)

```shell
TypeError: Command.__init__() got an unexpected keyword argument 'goto'
```

### Description

When I try to implement like below it's working:
return Command(send=Send(goto_node, {"messages": state['messages']}), update={"messages": [ai_msg, tool_msg]})

### System Info

Using the latest version of langgraph

**Comment by Saisiva123** [comment]
Could you please update the documentation: https://langchain-ai.github.io/langgraph/how-tos/agent-handoffs/#implement-handoffs-using-command

**Comment by hinthornw** [comment]
I believe your langgraph version is out of date.

**Comment by vbarda** [comment]
Yes, `send` is not an argument in `Command` in the latest library version

**Comment by Saisiva123** [comment]
Actually, if I use the 'goto' parameter then its throwing the error, I think it's working in V0.2.60.  In the latest version when I tried with 'send' parameter it is working as expected. 

So, it would be better if you please update the documentation accordingly so that there wouldn't be any confusion.

**Comment by vbarda** [comment]
can you try reinstalling in a fresh virtual environment?

**Comment by Saisiva123** [comment]
yeah, my bad, I think 'goto' parameter is working in the latest version as well. Could you please confirm the latest version please, I believe its V0.2.60?

**Comment by vbarda** [comment]
Yes, latest version is 0.2.60, glad it's working!
